import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))

X = np.array([1, 2, 3, 4]).reshape(2, 2)
Y = np.array([5, 6, 7, 8]).reshape(2, 2)
print(X)
print(Y)

print(X + Y)
print(X - Y)
print(X * Y)
print(X / Y)

print(np.sqrt(x))
print(np.exp(x))
print(np.power(x, 2))

print()
print('average of all:', X.mean())
print()
print('average of colums:', X.mean(axis=0))
print('average of rows:', X.mean(axis=1))
print()
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

print()
print('3 *X = \n', 3* X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)

print()
print()
Y = np.arange(9).reshape(3, 3)
print(X)

x = np.arange(3)
print(x)

print(Y + x)

print()
z = np.arange(3).reshape(3, 1)
print(z)
print(z + Y)